version: '3.8'

networks:
  my-network:

services:
  postgres:
    image: postgres:latest
    container_name: new-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: export-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgresql:/var/lib/postgresql
    networks:
      - my-network
  old-db:
    image: postgres:latest
    container_name: old-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: old-system-db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./storage/postgresql2:/var/lib/postgresql
    networks:
      - my-network
